### ISSUE TITLE
Commutes not clearing from screen after hoursEnd

### ISSUE THREAD

**Issue by OBoudreaux** [saml-dev/MMM-Traffic#104]
Commute times are updated during the window between "hoursStart" and "hoursEnd." The problem is that they aren't cleared from the screen outside of the window unless the browser is manually refreshed. (in server mode at least)

I have multiple commutes set up, some overlapping and some not, and over time, they are all displayed. I haven't checked to see if this is true over the "days" attribute as well.

**Comment by saml-dev** [comment]
Sorry for the delay, I don't actually have a smart mirror anymore :P are you still seeing this bug?

**Comment by OBoudreaux** [comment]
I decided to put my smart mirror functions into a homeassistant dashboard instead. So, no idea. Thanks for the reply though!
