### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by Prince-Hector** [saml-dev/MMM-Traffic#106]
heyho, thanks a lot four your awesome module and your support. After installation and customization everything is working. But i've seen some colors depending on traffic. So is it possible to get a green text when there is no traffic on my way to work - get a yellow/ red text when there is a little/ hard traffic on my way?

here my config-text. Thanks a lot

{
			module: "MMM-Traffic",
			position: "top_right",
			config: {
				accessToken: "xxx",
				originCoords: "xxx,yyy",
				destinationCoords: "xxx,yyy",
				showSymbol: true,
				firstLine: "{duration} mins",
				secondLine: "Home To Work 1",
				}
		},
		{
			module: "MMM-Traffic",
			position: "top_right",
			config: {
				accessToken: "xxx",
				originCoords: "xxx,yyy",
				destinationCoords: "xxx,yyy",
				showSymbol: true,
				firstLine: "{duration} mins",
				secondLine: "Home To Work 2",
				}
		},

**Comment by saml-dev** [comment]
When I updated this module to use mapbox instead of google maps, that feature was deprecated because mapbox doesn't provide any value to represent how "bad" the traffic is.

**Comment by Prince-Hector** [comment]
Ok, thanks. Can I do it manually in the CSS?

**Comment by saml-dev** [comment]
Yes you can apply your own styles, check out the [Styling section of the readme](https://github.com/saml-dev/MMM-Traffic#styling). You're on your own for figuring out when traffic is bad though. It should be possible to parse the text with javascript for the travel time and then you can just set limits based on your own knowledge of your route.

**Comment by Prince-Hector** [comment]
Ok, do u have an example for me?

**Comment by saml-dev** [comment]
There's a link to a style example in my last comment

**Comment by Prince-Hector** [comment]
yeah i've seen the link. but there is no parameter with "driving-time". so maybe you have a code like:
if driving-time > 50 min then display the text in color yellow.
thanks

**Comment by linkiln** [comment]
Hi, 

I've added to code part which is changing color of text to red when time is larger than 50 minutes. Chat GPT helped me with that.

` // Determine color based on duration
    **let color = this.duration > 50 ? "red" : "white";**

    // first line
    var firstLineText = document.createElement('span');
    firstLineText.innerHTML = this.loading ? this.config.loadingText : this.replaceTokens(this.config.firstLine);
    **firstLineText.style.color = color; // Apply color change**
    firstLineDiv.appendChild(firstLineText);
    wrapper.appendChild(firstLineDiv);
    if (this.loading) return wrapper;

    // second line
    if (this.config.secondLine) {
        secondLineDiv.innerHTML = this.replaceTokens(this.config.secondLine);
        **secondLineDiv.style.color = color; // Apply color change**
        wrapper.appendChild(secondLineDiv);
    }`
