### ISSUE TITLE
strange icon

### ISSUE THREAD

**Issue by 1Cedric1** [saml-dev/MMM-Traffic#107]
Dear @saml-dev ,
thank you first for your great module! it's a pleasure to see it running well.
Do you maybe know what the red icon on the attached printscreen means?
It appeared after a while and keeps staying there.
Thank you in advance for your reply.
Kind regards,
Cédric 
![IMG_20230416_135327_HDR](https://user-images.githubusercontent.com/61581150/232383055-e9cb7e67-28f3-4cd5-8e10-7d4f3446ef7e.jpg)

**Comment by saml-dev** [comment]
Hi there, I think you've got it mixed up with another module. MMM-Traffic doesn't provide a map of any kind :)
